name: dough_timer_app
description: A dough timer app for bakers
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: any

  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.6
  just_audio: ^0.9.17  # Updated just_audio package version
  audio_session: ^0.1.7  # Audio session for handling audio focus
  audioplayers: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0  # Added flutter_lints package
  flutter_launcher_icons: ^0.14.1  # Include flutter_launcher_icons for app icon generation

flutter:
  uses-material-design: true

  assets:
    - assets/digital.wav
    - assets/logo.png

fonts:
  - family: Roboto
    fonts:
      - asset: fonts/Roboto-Regular.ttf
      - asset: fonts/Roboto-Bold.ttf
        weight: 700


